<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>txt</string>
        <string>dokuwiki</string>
    </array>

    <key>name</key>
    <string>DokuWiki ST3</string>


    <key>patterns</key>
    <array>


        <!-- HEADINGS -->

        <dict>
            <key>comment</key>
            <string>====== heading ======</string>

            <key>name</key>
            <string>markup.heading.dokuwiki_st3</string>

            <key>match</key>
            <string>^\s*(={2,6})(.*)(\1)\s*$\n?</string>

            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>markup.heading.dokuwiki_st3</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>markup.heading.dokuwiki_st3</string>
                </dict>
            </dict>
        </dict>


        <!-- HORIZONTAL RULE -->

        <dict>
            <key>comment</key>
            <string>---- creates a horizontal rule</string>

            <key>match</key>
            <string>^\s*-{4,}\s*$</string>

            <key>name</key>
            <string>markup.separator.dokuwiki_st3</string>
        </dict>


        <!-- ~~NOTOC~~ -->

        <dict>
            <key>comment</key>
            <string>~~NOTOC~~ disables TOC for this page</string>

            <key>match</key>
            <string>~~NOTOC~~</string>

            <key>name</key>
            <string>markup.keyword.control.notoc.dokuwiki_st3</string>
        </dict>


        <!-- ~~NOCACHE~~ -->

        <dict>
            <key>comment</key>
            <string>~~NOCACHE~~ disables cache for this page</string>

            <key>match</key>
            <string>~~NOCACHE~~</string>

            <key>name</key>
            <string>markup.keyword.control.nocache.dokuwiki_st3</string>
        </dict>


        <!-- INCLUDES -->

        <dict>
            <key>include</key>
            <string>#inline</string>

            <key>comment</key>
            <string>Include 'inline' items from repository below</string>
        </dict>

    </array>


 <!-- ########################################################################### -->
 <!-- ########################################################################### -->
 <!-- ########################################################################### -->
 <!-- ########################################################################### -->
 <!-- ########################################################################### -->
 <!-- ########################################################################### -->
 <!-- ########################################################################### -->

    <key>repository</key>
    <dict>

        <key>inline</key>
        <dict>
            <key>patterns</key>
            <array>

                <!-- CODE BLOCKS -->
                <dict>
                    <key>include</key>
                    <string>#code</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#code2</string>
                </dict>

                <!-- EMOTICONS -->
                <dict>
                    <key>include</key>
                    <string>#emoticon</string>
                </dict>

                <!-- MONOSPACED TEXT -->
                <dict>
                    <key>include</key>
                    <string>#monospace</string>
                </dict>

                <!-- BOLD -->
                <dict>
                    <key>include</key>
                    <string>#bold</string>
                </dict>

                <!-- ITALICS -->
                <dict>
                    <key>include</key>
                    <string>#italic</string>
                </dict>

            </array>
        </dict>


        <key>emoticon</key>
        <dict>
            <!-- highlight the actual emoticon -->
            <key>name</key>
            <string>markup.emoticon.dokuwiki_st3</string>

            <key>match</key>
            <string>(FIXME!|FIXME|DELETEME!|DELETEME|LOL|8-\)|8-O|:-\(|:-\)|=\)|:-/|:-\\|:-\?|:-D|:-P|:-O|:-X|:-\||;-\)|\^_\^|:\?:|:!:)</string>
        </dict>


        <key>monospace</key>
        <dict>
            <!-- highlight the actual monospaced text -->
            <key>name</key>
            <string>markup.monospace.dokuwiki_st3</string>

            <key>begin</key>
            <string>('')</string>
            <key>end</key>
            <string>(\1)</string>

            <key>captures</key>
            <dict>
                <!-- fade out the 'containers' (apostrophe's) -->
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>markup.container.inline.dokuwiki_st3</string>
                </dict>
            </dict>

            <!-- allow other inline styles -->
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#inline</string>
                </dict>
            </array>
        </dict>


        <key>bold</key>
        <dict>
            <!-- highlight the actual bold text -->
            <key>name</key>
            <string>markup.bold.dokuwiki_st3</string>

            <key>begin</key>
            <string>(\*\*)</string>
            <key>end</key>
            <string>(\1)</string>

            <key>captures</key>
            <dict>
                <!-- fade out the 'containers' (double asterisks) -->
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>markup.container.inline.dokuwiki_st3</string>
                </dict>
            </dict>

            <!-- allow other inline styles -->
            <key>patterns</key>
            <array>
                <dict>
                    <!-- highlight any italic sub-text -->
                    <key>name</key>
                    <string>markup.bolditalic.dokuwiki_st3</string>

                    <key>begin</key>
                    <string>(?&lt;!:)//</string>
                    <key>end</key>
                    <string>(?&lt;!:)//</string>

                    <key>captures</key>
                    <dict>
                        <!-- fade out the 'containers' (double slash) -->
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>markup.container.inline.dokuwiki_st3</string>
                        </dict>
                    </dict>
                </dict>

                <dict>
                    <key>include</key>
                    <string>#inline</string>
                </dict>
            </array>
        </dict>


        <!-- TODO:  Fix incorrect url recognition?

            In text like '//As an example, I propose://'
            the final // would not cancel italics because it would currently
            be recognised as part of an url.
            Current workaround: place a space after the :
        -->
        <key>italic</key>
        <dict>
            <!-- highlight the actual italic text -->
            <key>name</key>
            <string>markup.italic.dokuwiki_st3</string>

            <key>begin</key>
            <string>(?&lt;!:)//</string>
            <key>end</key>
            <string>(?&lt;!:)//</string>

            <key>captures</key>
            <dict>
                <!-- fade out the 'containers' (double slash) -->
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>markup.container.inline.dokuwiki_st3</string>
                </dict>
            </dict>

            <!-- allow other inline styles -->
            <key>patterns</key>
            <array>
                <dict>
                    <!-- highlight any bold sub-text -->
                    <key>name</key>
                    <string>markup.bolditalic.dokuwiki_st3</string>

                    <key>begin</key>
                    <string>(\*\*)</string>
                    <key>end</key>
                    <string>(\1)</string>

                    <key>captures</key>
                    <dict>
                        <!-- fade out the 'containers' (double asterisks) -->
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>markup.container.inline.dokuwiki_st3</string>
                        </dict>
                    </dict>
                </dict>

                <dict>
                    <key>include</key>
                    <string>#inline</string>
                </dict>
            </array>
        </dict>


        <key>code</key>
        <dict>
            <!-- style the code container -->
            <key>name</key>
            <string>markup.container.code.dokuwiki_st3</string>

            <key>begin</key>
            <string>(&lt;(code|CODE|file|FILE)(\s*.*\s){0,1}(.*[.]{0,1}.*)&gt;)</string>
            <key>end</key>
            <string>(&lt;/(code|CODE|file|FILE)&gt;).*\n</string>

            <key>captures</key>
            <dict>
                <!-- fade out the code tags -->
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>markup.container.block.dokuwiki_st3</string>
                </dict>
                <!-- highlight the language identifier eg. php -->
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>markup.code.type.dokuwiki_st3</string>
                </dict>
                <!-- highlight a filename if specified -->
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>markup.filename.dokuwiki_st3</string>
                </dict>
            </dict>

            <!-- apply specific code types -->
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>source.php</string>
                </dict>
            </array>
        </dict>
        <key>code2</key>
        <dict>
            <!-- code line with 2 spaces -->
            <key>match</key>
            <string>^((\s\s)|(\t))[^\*\-].*$</string>
            <key>name</key>
            <string>markup.container.code.dokuwiki_st3</string>
        </dict>
    </dict>



    <key>scopeName</key>
    <string>text.html.dokuwiki_st3</string>

    <key>uuid</key>
    <string>dc3d438f-8237-400b-b25d-19cb3bbdc508</string>
</dict>
</plist>
